require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'

# Style preferences
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Metrics
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/AbcSize:
  Max: 20

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/**/*'

# Rails specific
Rails/I18nLocaleTexts:
  Enabled: false

# RSpec specific
RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10
